import { StyleSheet, Platform } from 'react-native';
import type { ThemeColors } from '../../theme/theme';

export const createStyles = (theme: ThemeColors) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    paddingTop: Platform.OS === 'ios' ? 50 : 16,
    backgroundColor: theme.header,
    borderBottomWidth: 1,
    borderBottomColor: theme.border,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: theme.inputBackground,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: theme.text,
    flex: 1,
    textAlign: 'center',
  },
  headerRight: {
    flexDirection: 'row',
  },
  headerButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: theme.inputBackground,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cameraContainer: {
    flex: 1,
  },
  camera: {
    flex: 1,
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
  },
  scanFrame: {
    width: 280,
    height: 280,
    borderWidth: 3,
    borderColor: theme.primary,
    borderRadius: 24,
    backgroundColor: 'transparent',
  },
  scanInstructions: {
    position: 'absolute',
    bottom: 100,
    left: 0,
    right: 0,
    alignItems: 'center',
    paddingHorizontal: 40,
  },
  instructionText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
    backgroundColor: 'rgba(0,0,0,0.6)',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 12,
  },
  eventSelectorButton: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 70 : 30,
    left: 16,
    right: 16,
    backgroundColor: theme.surface,
    borderRadius: 12,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: theme.border,
  },
  eventSelectorText: {
    color: theme.text,
    fontSize: 14,
    fontWeight: '600',
    flex: 1,
  },
  manualInputButton: {
    position: 'absolute',
    bottom: 40,
    left: 16,
    right: 16,
    backgroundColor: theme.surface,
    borderRadius: 12,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: theme.border,
  },
  manualInputButtonText: {
    color: theme.text,
    fontSize: 15,
    fontWeight: '600',
    marginLeft: 8,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.7)',
  },
  modalContent: {
    backgroundColor: theme.surface,
    borderRadius: 24,
    padding: 24,
    width: '85%',
    maxWidth: 400,
    borderWidth: 1,
    borderColor: theme.border,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: theme.text,
    marginBottom: 16,
    textAlign: 'center',
  },
  input: {
    backgroundColor: theme.inputBackground,
    borderRadius: 12,
    padding: 14,
    fontSize: 16,
    color: theme.text,
    borderWidth: 1,
    borderColor: theme.border,
    marginBottom: 16,
  },
  modalButtons: {
    flexDirection: 'row',
  },
  modalButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
  },
  cancelButton: {
    backgroundColor: theme.inputBackground,
    borderWidth: 1,
    borderColor: theme.border,
  },
  cancelButtonText: {
    color: theme.text,
    fontWeight: '700',
  },
  submitButton: {
    backgroundColor: theme.primary,
  },
  submitButtonText: {
    color: theme.buttonPrimaryText,
    fontWeight: '700',
  },
  resultModalContent: {
    backgroundColor: theme.surface,
    borderRadius: 24,
    padding: 28,
    width: '85%',
    maxWidth: 400,
    borderWidth: 1,
    borderColor: theme.border,
  },
  successIcon: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: 'rgba(76, 217, 100, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(76, 217, 100, 0.22)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  errorIcon: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: 'rgba(255, 79, 216, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(255, 79, 216, 0.22)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  resultIconContainer: {
    alignItems: 'center',
    marginBottom: 12,
  },
  resultTitle: {
    color: theme.text,
    fontWeight: '900',
    fontSize: 18,
  },
  resultMessage: {
    color: theme.textMuted,
    textAlign: 'center',
    marginBottom: 14,
  },
  resultButton: {
    backgroundColor: theme.primary,
    paddingVertical: 14,
    borderRadius: 999,
    alignItems: 'center',
  },
  resultButtonText: {
    color: theme.buttonPrimaryText,
    fontWeight: '900',
  },
  secondaryButton: {
    marginTop: 10,
    borderWidth: 1,
    borderColor: theme.border,
    paddingVertical: 14,
    borderRadius: 999,
    alignItems: 'center',
    backgroundColor: theme.inputBackground,
  },
  secondaryButtonText: {
    color: theme.text,
    fontWeight: '800',
  },
  eventSelectorModal: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  eventSelectorContent: {
    backgroundColor: theme.surface,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    maxHeight: '70%',
    borderWidth: 1,
    borderColor: theme.border,
  },
  eventSelectorHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  eventSelectorTitle: {
    color: theme.text,
    fontWeight: '800',
    fontSize: 18,
  },
  eventItem: {
    borderRadius: 12,
    padding: 16,
    marginBottom: 8,
    borderWidth: 1,
  },
  eventItemSelected: {
    backgroundColor: theme.primary + '20',
    borderColor: theme.primary,
  },
  eventItemUnselected: {
    backgroundColor: theme.inputBackground,
    borderColor: theme.border,
  },
  eventItemText: {
    color: theme.text,
  },
  eventItemTextSelected: {
    fontWeight: '700',
  },
  eventItemTextUnselected: {
    fontWeight: '500',
  },
  eventItemCheck: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  eventItemCheckText: {
    color: theme.primary,
    fontSize: 12,
    marginLeft: 4,
  },
  historyModal: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  historyContent: {
    flex: 1,
    backgroundColor: theme.background,
    marginTop: 60,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderWidth: 1,
    borderColor: theme.border,
  },
  historyHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: theme.border,
  },
  historyTitle: {
    color: theme.text,
    fontWeight: '800',
    fontSize: 18,
  },
  historyEmpty: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 40,
  },
  historyEmptyText: {
    color: theme.textMuted,
    marginTop: 16,
    textAlign: 'center',
  },
  historyItem: {
    backgroundColor: theme.surface,
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: theme.border,
  },
  historyItemHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  historyItemContent: {
    flex: 1,
  },
  historyItemName: {
    color: theme.text,
    fontWeight: '700',
    fontSize: 16,
    marginBottom: 4,
  },
  historyItemDetail: {
    color: theme.textMuted,
    fontSize: 12,
    marginBottom: 2,
  },
  undoButton: {
    backgroundColor: theme.error + '20',
    borderRadius: 8,
    padding: 8,
  },
});
