import { StyleSheet, Platform } from 'react-native';
import type { ThemeColors } from '../../theme/theme';

export const createStyles = (theme: ThemeColors) => StyleSheet.create({
  container: { 
    flex: 1,
    backgroundColor: theme.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    paddingTop: Platform.OS === 'ios' ? 50 : 16,
    borderBottomWidth: 1,
    backgroundColor: theme.header,
    borderBottomColor: theme.border,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '600',
    textAlign: 'center',
    flex: 1,
    color: theme.text,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.inputBackground,
  },
  content: {
    flex: 1,
    padding: 16,
  },
  sectionTitle: {
    fontSize: 17,
    fontWeight: '600',
    marginTop: 24,
    marginBottom: 16,
    letterSpacing: 0.2,
    color: theme.textSecondary,
  },
  row: {
    flexDirection: 'row',
  },
  inputGroup: {
    marginBottom: 20,
  },
  label: {
    fontSize: 14,
    marginBottom: 10,
    fontWeight: '500',
    color: theme.textMuted,
  },
  locationInput: {
    position: 'relative',
  },
  inputIcon: {
    position: 'absolute',
    left: 12,
    top: 16,
    zIndex: 1,
  },
  input: {
    borderRadius: 12,
    padding: 16,
    fontSize: 16,
    borderWidth: 1,
    backgroundColor: theme.inputBackground,
    borderColor: theme.border,
    color: theme.text,
  },
  dateInput: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    backgroundColor: theme.inputBackground,
    borderColor: theme.border,
  },
  dateText: {
    fontSize: 16,
    color: theme.textMuted,
  },
  textArea: {
    height: 140,
    textAlignVertical: 'top',
    paddingTop: 12,
    lineHeight: 22,
  },
  imageUpload: {
    borderRadius: 12,
    borderWidth: 1.5,
    borderStyle: 'dashed',
    padding: 32,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 24,
    backgroundColor: theme.inputBackground,
    borderColor: theme.border,
  },
  uploadText: {
    fontSize: 15,
    fontWeight: '500',
    marginTop: 14,
    marginBottom: 6,
    color: theme.primary,
  },
  uploadSubtext: {
    fontSize: 12,
    color: theme.textMuted,
  },
  categorySelector: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    backgroundColor: theme.inputBackground,
    borderColor: theme.border,
  },
  categorySelectorContent: {
    flex: 1,
  },
  categorySelectorText: {
    fontSize: 16,
    fontWeight: '500',
    color: theme.text,
  },
  categorySelectorSubtext: {
    fontSize: 12,
    marginTop: 4,
    color: theme.textMuted,
  },
  categorySelectorPlaceholder: {
    fontSize: 16,
    color: theme.textMuted,
  },
  defaultImageContainer: {
    position: 'relative',
    width: '100%',
  },
  coverImagePreview: {
    width: '100%',
    height: 180,
    borderRadius: 12,
  },
  removeImageButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    marginTop: -16,
    marginBottom: 16,
  },
  removeImageText: {
    fontSize: 14,
    fontWeight: '500',
    marginLeft: 6,
    color: theme.error,
  },
  toggleContainer: {
    flexDirection: 'row',
    borderRadius: 12,
    padding: 5,
    marginBottom: 20,
    borderWidth: 1,
    backgroundColor: theme.inputBackground,
    borderColor: theme.border,
  },
  toggleButton: {
    flex: 1,
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
  toggleButtonActive: {
    backgroundColor: theme.border,
  },
  toggleText: {
    fontWeight: '500',
    fontSize: 15,
  },
  toggleTextActive: {
    fontWeight: '600',
  },
  priceInput: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  publishButton: {
    borderRadius: 12,
    padding: 18,
    alignItems: 'center',
    marginTop: 24,
    marginBottom: 12,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
    backgroundColor: theme.primary,
  },
  publishButtonDisabled: {
    opacity: 0.7,
  },
  publishButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: theme.buttonPrimaryText,
  },
  draftButton: {
    padding: 12,
    alignItems: 'center',
    marginBottom: 40,
  },
  draftButtonText: {
    fontSize: 15,
    fontWeight: '500',
    color: theme.primary,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: '80%',
    paddingBottom: Platform.OS === 'ios' ? 40 : 20,
    backgroundColor: theme.header,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: theme.border,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: theme.text,
  },
  modalLoader: {
    padding: 40,
  },
  categoryItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: theme.border,
  },
  categoryItemSelected: {
    backgroundColor: theme.inputBackground,
  },
  categoryItemContent: {
    flex: 1,
  },
  categoryItemName: {
    fontSize: 16,
    fontWeight: '500',
    color: theme.textMuted,
  },
  categoryItemNameSelected: {
    fontWeight: '600',
    color: theme.primary,
  },
  categoryItemDescription: {
    fontSize: 12,
    marginTop: 4,
    color: theme.textMuted,
  },
});
